services:
  MySQL:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-db:latest
    healthcheck:
      test: "mysqladmin ping --silent"
      interval: "5s"
    ports:
      - "3306:3306"
    security_opt:
    - seccomp:unconfined
    networks:
      - utopia_nw
        
  user:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-users:jenkins-auto-build-users
    depends_on:
      MySQL:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      - DB-LOC=jdbc:mysql://MySQL:3306/utopia
    networks:
      - utopia_nw
        
  booking:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-booking:jenkins-auto-build-booking
    depends_on:
      MySQL:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - DB-LOC=jdbc:mysql://MySQL:3306/utopia
    networks:
      - utopia_nw
        
  flight:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-flights:jenkins-auto-build-flights
    depends_on:
      MySQL:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - DB-LOC=jdbc:mysql://MySQL:3306/utopia
    networks:
        - utopia_nw
        


networks:
  utopia_nw:

