version: '2'

services:
        
  user:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-users:jenkins-auto-build-users
    ports:
      - "8083:8083"
    environment:
      - UTOPIA_DB_UNAME="${UTOPIA_DB_UNAME}"
      - UTOPIA_DB_PASS="${UTOPIA_DB_PASS}"
      - DB_LOC="${DB_LOC}"
    networks:
      - utopia_nw
        
  booking:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-booking:jenkins-auto-build-booking
    ports:
      - "8081:8081"
    environment:
      - UTOPIA_DB_UNAME="${UTOPIA_DB_UNAME}"
      - UTOPIA_DB_PASS="${UTOPIA_DB_PASS}"
      - DB_LOC="${DB_LOC}"
    networks:
      - utopia_nw
        
  flight:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-flights:jenkins-auto-build-flights
    ports:
      - "8082:8082"
    environment:
      - UTOPIA_DB_UNAME="${UTOPIA_DB_UNAME}"
      - UTOPIA_DB_PASS="${UTOPIA_DB_PASS}"
      - DB_LOC="${DB_LOC}"
    networks:
        - utopia_nw

networks:
  utopia_nw:

