version: '2'

services:
        
  user:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-users:jenkins-auto-build-users
    ports:
      - "8083:8083"
    environment:
      - UTOPIA_DB_UNAME=admin
      - UTOPIA_DB_PASS=09132021SmoothStack!
      - DB_LOC=jdbc:mysql://utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com:3306/cb-utopia
    networks:
      - utopia_nw
        
  booking:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-booking:jenkins-auto-build-booking
    ports:
      - "8081:8081"
    environment:
      - UTOPIA_DB_UNAME=admin
      - UTOPIA_DB_PASS=09132021SmoothStack!
      - DB_LOC=jdbc:mysql://utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com:3306/cb-utopia
    networks:
      - utopia_nw
        
  flight:
    image: 902316339693.dkr.ecr.us-east-2.amazonaws.com/cb-flights:jenkins-auto-build-flights
    ports:
      - "8082:8082"
    environment:
      - UTOPIA_DB_UNAME=admin
      - UTOPIA_DB_PASS=09132021SmoothStack!
      - DB_LOC=jdbc:mysql://utopia.cztkke9ur9zz.us-east-2.rds.amazonaws.com:3306/cb-utopia
    networks:
        - utopia_nw

networks:
  utopia_nw:

